export const MANUAL_PROJECTS = [
  {
    id: "manual-101",
    client_name: "Andheri",
    location: "Andheri",
    project_status: "Completed",
    category: "Residential",
    zone: "Central Suburbs",
    completion_date: "2025",
    featured_image: null,
    lat: 19.1144,
    long: 72.867943,
    lng: 72.8679,
    state: "Maharashtra",
    country: "India",
    description: "Mulund project location.",
    is_manual: true,
  },

  {
    id: "manual-102",
    client_name: "Mulund Project 2",
    location: "Mulund",
    project_status: "In Progress",
    category: "Residential",
    zone: "Central Suburbs",
    completion_date: "2026",
    featured_image: null,
    lat: 19.1760,
    long: 72.9590,
    lng: 72.9590,
    state: "Maharashtra",
    country: "India",
    description: "Mulund project location.",
    is_manual: true,
  },

  {
    id: "manual-103",
    client_name: "Mulund Project 3",
    location: "Mulund",
    project_status: "Upcoming",
    category: "Residential",
    zone: "Central Suburbs",
    completion_date: "2027",
    featured_image: null,
    lat: 19.1698,
    long: 72.9542,
    lng: 72.9542,
    state: "Maharashtra",
    country: "India",
    description: "Mulund project location.",
    is_manual: true,
  },

  {
    id: "manual-201",
    client_name: "Navi Mumbai Project 1",
    location: "Navi Mumbai",
    project_status: "Completed",
    category: "Commercial",
    zone: "Navi Mumbai",
    completion_date: "2025",
    featured_image: null,
    lat: 19.0330,
    long: 73.0290,
    lng: 73.0290,
    state: "Maharashtra",
    country: "India",
    description: "Navi Mumbai project location.",
    is_manual: true,
  },

  {
    id: "manual-202",
    client_name: "Navi Mumbai Project 2",
    location: "Navi Mumbai",
    project_status: "In Progress",
    category: "Residential",
    zone: "Navi Mumbai",
    completion_date: "2026",
    featured_image: null,
    lat: 19.0285,
    long: 73.0350,
    lng: 73.0350,
    state: "Maharashtra",
    country: "India",
    description: "Navi Mumbai project location.",
    is_manual: true,
  },

  {
    id: "manual-301",
    client_name: "Bandra Project 1",
    location: "Bandra West",
    project_status: "Completed",
    category: "Residential",
    zone: "Western Suburbs",
    completion_date: "2025",
    featured_image: null,
    lat: 19.0544,
    long: 72.8398,
    lng: 72.8398,
    state: "Maharashtra",
    country: "India",
    description: "Bandra project location.",
    is_manual: true,
  },

  {
    id: "manual-302",
    client_name: "Bandra Project 2",
    location: "Bandra West",
    project_status: "Upcoming",
    category: "Residential",
    zone: "Western Suburbs",
    completion_date: "2027",
    featured_image: null,
    lat: 19.0580,
    long: 72.8420,
    lng: 72.8420,
    state: "Maharashtra",
    country: "India",
    description: "Bandra project location.",
    is_manual: true,
  },
];